name = "multicomponent-eos"
version = "0.1.0"
license = "MIT"
author = "Federico Benelli"
maintainer = "federico.benelli@mi.unc.edu.ar"
copyright = "Copyright 2022, Federico Benelli"

[build]
link = ["lapack", "blas"]
auto-executables = true
auto-tests = true
auto-examples = true

[install]
library = false

[dependencies]
ftools.git = "https://github.com/fedebenelli/ftools"

[dev-dependencies]
# Testing dependencies
test-drive.git = "https://github.com/fortran-lang/test-drive"
